/data03/home/wangmingcheng/anaconda3/bin/vcftools --gzvcf /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/09.Exclude_Filtered_Variants/final_snp.vcf.gz --plink --out /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/plink
/data03/home/wangmingcheng/bin/plink --noweb --file /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/plink --geno 0.05 --maf 0.05 --hwe 0.0001 --make-bed --out /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/admixture
/data03/home/wangmingcheng/bin/admixture --cv -j10 /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/admixture.bed 2 > /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/log2.out
/data03/home/wangmingcheng/bin/admixture --cv -j10 /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/admixture.bed 3 > /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/log3.out
/data03/home/wangmingcheng/bin/admixture --cv -j10 /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/admixture.bed 4 > /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/log4.out
/data03/home/wangmingcheng/bin/admixture --cv -j10 /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/admixture.bed 5 > /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/log5.out
/data03/home/wangmingcheng/bin/admixture --cv -j10 /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/admixture.bed 6 > /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/log6.out
/data03/home/wangmingcheng/bin/admixture --cv -j10 /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/admixture.bed 7 > /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/log7.out
/data03/home/wangmingcheng/bin/admixture --cv -j10 /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/admixture.bed 8 > /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/log8.out
/data03/home/wangmingcheng/bin/admixture --cv -j10 /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/admixture.bed 9 > /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/log9.out
/data03/home/wangmingcheng/bin/admixture --cv -j10 /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/admixture.bed 10 > /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/log10.out
/data03/home/wangmingcheng/bin/admixture --cv -j10 /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/admixture.bed 11 > /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/log11.out
/data03/home/wangmingcheng/bin/admixture --cv -j10 /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/admixture.bed 12 > /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/log12.out
/data03/home/wangmingcheng/bin/admixture --cv -j10 /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/admixture.bed 13 > /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/log13.out
/data03/home/wangmingcheng/bin/admixture --cv -j10 /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/admixture.bed 14 > /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/log14.out
/data03/home/wangmingcheng/bin/admixture --cv -j10 /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/admixture.bed 15 > /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure/log15.out
cd /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure && awk '/CV/ {print $3,$4}' *out | cut -c 4,7-20 > admixture.cv.error
cd /data03/home/wangmingcheng/project/cherry_genome_hic/red_reference_reseq/Population_structure && Rscript /data03/home/wangmingcheng/pipeline/v5.0/bin/plotADMIXTURE.r -p admixture -i admixture.nosex -k 10 -l A13-33,caihong,caixia,dalong,hongmi,jiahong,leini,mingzhu,Royalann,xiangquanyihao,yeluying,yezaohuangpi,yuzhou,Wild,R01,R02,R03,R04,R05,R06,R07,R08,R09,R10,R11,R12,R13,R14,R15,R16,R17,R18,R19,R20,R21,R22,R23,R24,hongmi_new,hongyan_new,labinsi_new,wanhongzhu_new
